version: '3'

services:
  auth_db:
    image: postgres
    restart: always
    volumes:
      - terapia_holistica_auth:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - "5432:5432"
volumes:
  terapia_holistica_auth: